name: WLED compile

on:
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio

    - name: Set up Node.js
      uses: actions/setup-node@v4

    - name: Run PlatformIO
      run: |
        rm -rf /tmp/WLEDtemp/* || true
        mkdir -p /tmp/WLEDtemp
        wget https://api.github.com/repos/Aircoookie/WLED/zipball/v0.15.0 -O /tmp/WLEDtemp/mm.zip
        unzip /tmp/WLEDtemp/mm.zip -d /tmp/WLEDtemp
        find /tmp/WLEDtemp -maxdepth 1 -mindepth 1 -name "*" -type d >> /tmp/WLEDtemp/wledfoldername
        cd `cat /tmp/WLEDtemp/wledfoldername`
        echo '[env:custom_build]' >> platformio.ini
        echo 'extends = env:esp32c3dev' >> platformio.ini
        echo 'build_flags = ${env:esp32c3dev.build_flags} -D LEDPIN=19 -D BTNPIN=8 -DARDUINO_USB_CDC_ON_BOOT=0 -D USERMOD_AUDIOREACTIVE -D sqrt_internal=sqrtf' >> platformio.ini
        echo 'lib_deps = kosme/arduinoFFT @ 2.0.1' >> platformio.ini
        echo '  ${env:esp32c3dev.lib_deps}' >> platformio.ini
        echo '  ${esp32.AR_lib_deps}' >> platformio.ini
        echo 'build_unflags= -D WLED_RELEASE_NAME' >> platformio.ini
        pio run -e custom_build || (echo "PlatformIO build failed" && exit 1)

    - name: Copy Files
      run: |
        cd $GITHUB_WORKSPACE
        git rm -r $GITHUB_WORKSPACE/*.bin || true
        WLEDFOLDERNAME=`cat /tmp/WLEDtemp/wledfoldername`
        if [ -f ${WLEDFOLDERNAME}/build_output/firmware/custom_build.bin ]; then
          cp ${WLEDFOLDERNAME}/build_output/firmware/custom_build.bin $GITHUB_WORKSPACE/
        else
          echo "Error: firmware/custom_build.bin not found."
          exit 1
        fi
        date -I | tr -d '\n' > $GITHUB_WORKSPACE/last_update_date.txt

    - name: Commit Files
      run: |
        cd $GITHUB_WORKSPACE
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        git add $GITHUB_WORKSPACE/custom_build.bin
        git add $GITHUB_WORKSPACE/last_update_date.txt
        git commit -m "Commit Custom Build"
        git push origin main
